spring:
  profiles:
    active: mongo
  application:
    name: DOSW-Library
  datasource:
    url: jdbc:postgresql://localhost:5432/dosw_library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb+srv://samuel:mongo1234@cluster0.qlpgzqc.mongodb.net/dosw_library?appName=Cluster0
      database: dosw_library
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: dosw-library-secret-key-for-jwt-signing-minimum-256-bits-2024
    expiration: 86400000
